FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080   
#puerto liberado

ENV ASPNETCORE_URLS=http://+:8080 
#variable ambiente puerto en que corre

USER app
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG configuration=Realease
WORKDIR /src
COPY ["ChatP2P.csproj","./"]
RUN dotnet restore "ChatP2P.csproj"
COPY . .
#mover carpeta
WORKDIR "/src/."
RUN dotnet build "ChatP2P.csproj" -c ${configuration} -o /app/build
#abrir terminalrun

FROM build AS publish
ARG configuration=Realease
RUN dotnet publish "ChatP2P.csproj" -c $configuration -o /app/publish /p:UseAppHost=false
#usar from como base y crear otra capa

FROM base AS final 
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT [ "dotnet","ChatP2P.dll"]